/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mayab.patrones.adapter;

import java.util.ArrayList;

/**
 *
 * @author galindo
 */
public class AdapterGUI extends javax.swing.JFrame {

    ArrayList<OldPerson> people = new ArrayList<OldPerson>();
    
    /**
     * Creates new form DAO
     */
    public AdapterGUI() {
        initComponents();
        this.setSize(500, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtN = new javax.swing.JTextField();
        jTxtFN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtLN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtAgeO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtAgeN = new javax.swing.JTextField();
        jBtnOld = new javax.swing.JButton();
        jBtnNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTxtN);
        jTxtN.setBounds(60, 70, 80, 26);
        getContentPane().add(jTxtFN);
        jTxtFN.setBounds(320, 70, 80, 26);

        jLabel1.setText("Old Person");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 80, 16);

        jLabel2.setText("New Person");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 20, 80, 16);

        jLabel3.setText("Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 50, 40, 16);

        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 70, 16);
        getContentPane().add(jTxtLN);
        jTxtLN.setBounds(60, 140, 80, 26);

        jLabel5.setText("Age:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 28, 16);
        getContentPane().add(jTxtAgeO);
        jTxtAgeO.setBounds(60, 210, 70, 26);

        jLabel6.setText("Full name:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 50, 70, 16);

        jLabel7.setText("Age:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 110, 28, 16);
        getContentPane().add(jTxtAgeN);
        jTxtAgeN.setBounds(320, 130, 80, 26);

        jBtnOld.setText("Submit");
        jBtnOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOldActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnOld);
        jBtnOld.setBounds(110, 260, 88, 29);

        jBtnNew.setText("Submit");
        jBtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNewActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNew);
        jBtnNew.setBounds(370, 180, 97, 29);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 220, 210, 132);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOldActionPerformed
        String name = jTxtN.getText();
        String last = jTxtLN.getText();
        String age = jTxtAgeO.getText();
        
        OldPerson old = new BabyBoomer(name,last,age);
        
        people.add(old);
        
        display();
    }//GEN-LAST:event_jBtnOldActionPerformed

    private void jBtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNewActionPerformed
        String name = jTxtFN.getText();
        String age = jTxtAgeN.getText();
        
        NewPerson me = new Millenian(name,age);
        
        OldPerson oldMe = new NewPersonAdapter(me);
        
        people.add(oldMe);
        
        display();
    }//GEN-LAST:event_jBtnNewActionPerformed

    public void display(){
        String[] ar = new String[people.size()];
        int i = 0;
        
        for(OldPerson old: people){
            ar[i] = old.name() + " - " + old.lastName() + " - " + old.dateBirth();
            i++;
        }
        jList1.setListData(ar);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdapterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdapterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdapterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdapterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdapterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnNew;
    private javax.swing.JButton jBtnOld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtAgeN;
    private javax.swing.JTextField jTxtAgeO;
    private javax.swing.JTextField jTxtFN;
    private javax.swing.JTextField jTxtLN;
    private javax.swing.JTextField jTxtN;
    // End of variables declaration//GEN-END:variables
}
